# test data

# Garden Parameters
amount_plants:
  default_value: &id003
    1
amount_plant_types:
  default_value: 1
garden_length:
  default_value: &id001
    60
garden_width:
  default_value: &id002
    60
sector_rows:
  default_value: 15
sector_cols:
  default_value: 30
garden_days:
    default_value: 100

max_water_content:
  default_value: 0.3
  #randomize:
  #  distribution_type: uniform
  #  multiplier_min: 0.98
  #  multiplier_max: 1.02
max_nutrient_content:
  default_value: 1.0
permanent_wilting_point:
  default_value: 0.0
init_water:
  default_value: 0.1
  randomize:
    distribution_type: truncated_normal
    scale: 0.04
    range_min: 0.0
    range_max: 0.3
init_water_mean:
  default_value: 0.2
init_water_scale:
  default_value: 0.04
evaporation_percent_mean:
  default_value: 0.04
evaporation_percent_scale:
  default_value: 0.0054
irrigation_amount:
  default_value: 0.0002

# Policy Parameters
water_threshold:
  default_value: 1.0
irr_health_window_width:
  default_value: 9
prune_window_rows:
  default_value: 5
prune_window_cols:
  default_value: 5
prune_rate:
  default_value: 0.15
prune_delay:
  default_value: 20

# Plant Parameters
reference_outer_radii: #['Green Lettuce', 'Red_Lettuce', 'Borage', 'Swiss Chard', 'Kale', 'Cilantro', 'Radicchio', 'Turnip']
  default_value: [25]
  dtype: np.int
  #randomize:
  #  distribution_type: truncated_normal
  #  scale: [2, 2, 2, 2, 2]
  #  range_min: [24., 24., 34., 31., 41., 23., 21., 34.]
  #  range_max: [32., 32., 42., 39., 49., 31., 29., 42.]
common_names:
  default_value: ['Green Lettuce']
x_coordinates:
  default_value: [30]
  dtype: np.int
  #randomize:
  #  distribution_type: random_coordinate
  #  range_min: 0.1
  #  range_max: *id001
  #  shape: *id003
y_coordinates:
  default_value: [30]
  dtype: np.int
  #randomize:
  #  distribution_type: random_coordinate
  #  range_min: 0.0
  #  range_max: *id002
  #  shape: *id003
current_outer_radii:
  default_value: [1]
  dtype: np.int
germination_times:
  default_value: [8]
  dtype: np.int
  #randomize:
  #  distribution_type: truncated_normal
  #  scale: [1,1,1,1,1,1,1,1]
  #  range_min: [1.0,1.0,1.0,1.0,1.0]
  #  range_max: [13., 15.,  9.,  9., 11., 13., 12., 10.]
maturation_times:
  default_value: [60]
  dtype: np.int
  #randomize:
  #  distribution_type: truncated_normal
  #  scale: [2, 2, 2, 2, 2, 2, 2, 2]
  #  range_min: [1.0,1.0,1.0,1.0,1.0]
  #  range_max: [63., 73., 63., 63., 73., 73., 58., 73.]
# Waiting = m=30 s=2 if "invasive" else m=10, s=2
waiting_times:
  default_value: [5]
  dtype: np.int
  #randomize:
  #  distribution_type: truncated_normal
  #  scale: [2, 2, 2, 2, 2, 2, 2, 2]
  #  range_min: [1.0,1.0,1.0,1.0,1.0]
  #  range_max: [100.0,100.0,100.0,100.0,100.0]
# Waiting = m=10 s=2 if "invasive" else m=20, s=2
wilting_times:
  default_value: [18]
  dtype: np.int
  #randomize:
  #  distribution_type: truncated_normal
  #  scale: [2, 2, 2, 2, 2, 2, 2, 2]
  #  range_min: [1., 1., 1., 1., 1., 1., 1., 1.]
  #  range_max: [20., 18., 20., 20., 18., 18., 20., 18.]
light_use_efficiencies:
  default_value: [1]
  dtype: np.float32
water_use_efficiencies:
  default_value: [0.14]
  dtype: np.float32
nutrients_use_efficiencies:
  default_value: [0.1]
  dtype: np.float32
tau:
  default_value: 0
overwatered_time_threshold:
  default_value: 5
underwatered_time_threshold:
  default_value: 5
overwatered_threshold:
  default_value: 100
underwaterd_threshold:
  default_value: 0.01